"""
version_gen.py - Automatic version generation for goTapFirmware

Generates version.h with GOTAP_VERSION macro in yyyy.mm.vv format.
- yyyy: Current year
- mm: Current month
- vv: Commit count since last tag (or 0 if no tags exist)

For development branch, adds '-dev' suffix.

This script is intended to be used as a PlatformIO extra_script.
Usage in platformio.ini: extra_scripts = pre:scripts/version_gen.py

Can also be run standalone: python scripts/version_gen.py
"""

import subprocess
import os
from datetime import datetime

def get_git_branch():
    """Get current Git branch name."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return "unknown"

def get_commit_count_since_tag():
    """Get commit count since last tag using git describe."""
    try:
        # --long ensures we always get commit count even if we're exactly on a tag
        # Format: TAG-N-HASH (e.g., v2026.03.0-5-g1234567)
        result = subprocess.run(
            ["git", "describe", "--tags", "--always", "--long"],
            capture_output=True,
            text=True,
            check=True
        )
        output = result.stdout.strip()
        
        # Parse the output to get commit count
        parts = output.split("-")
        if len(parts) >= 2 and parts[-2].isdigit():
            return parts[-2]  # Commit count
        return "0"
    except subprocess.CalledProcessError:
        # No tags exist, count all commits
        try:
            result = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"],
                capture_output=True,
                text=True,
                check=True
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError:
            return "0"

def generate_version():
    """Generate version string in yyyy.mm.vv format."""
    now = datetime.now()
    year = now.year
    month = now.month
    
    commit_count = get_commit_count_since_tag()
    
    branch = get_git_branch()
    is_dev_branch = branch in ["development", "dev"]
    
    version = f"{year}.{month:02d}.{commit_count}"
    if is_dev_branch:
        version += "-dev"
    
    return version

def generate_version_header(version, include_dir):
    """Generate version.h file."""
    version_header_path = os.path.join(include_dir, "version.h")
    
    version_content = f'''/**
 * @file version.h
 * @brief Auto-generated firmware version header.
 * 
 * DO NOT EDIT - This file is automatically generated by scripts/version_gen.py
 * Version format: yyyy.mm.vv[-dev]
 */

#pragma once

#define GOTAP_VERSION "{version}"
'''
    
    os.makedirs(include_dir, exist_ok=True)
    with open(version_header_path, "w") as f:
        f.write(version_content)
    
    return version_header_path

def main():
    version = generate_version()
    
    # Try to import PlatformIO environment
    try:
        Import("env")  # noqa: F821
        is_platformio = True
    except NameError:
        is_platformio = False
    
    if is_platformio:
        # Get include directory from PlatformIO
        include_dir = os.path.join(env.subst("$PROJECT_DIR"), "include")  # noqa: F821
    else:
        # Standalone mode - use script's project directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_dir = os.path.dirname(script_dir)
        include_dir = os.path.join(project_dir, "include")
    
    # Generate version.h file
    version_path = generate_version_header(version, include_dir)
    print(f"[version_gen.py] Generated GOTAP_VERSION: {version} -> {version_path}")

# Run the script
main()
